#!/bin/sh

if [[ $# -eq 1 ]] ; then
  selected=$1
else
  selected=$(find ~/wallpapers -mindepth 1 -maxdepth 1 -type f | fzf)
fi

if [[ -z $selected ]] ; then
  exit 0
fi

feh --no-fehbg --bg-scale $selected
# feh --no-fehbg --bg-scale '/home/rocha/Downloads/bh-cartoon.jpg' 
