#!/usr/bin/env zsh

mkdir -p $HOME/.config

FOLDERS=".config,.gitconfig,.tmux.conf,.zshrc"
for folder in $(echo $FOLDERS | sed "s/,/ /g")
do
  echo "stowing $folder"
  stow $folder -t $HOME/$folder
done
