[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
opacity = 1.0

[font]
size = 15.0
# normal = { family = "Fira Code Nerd Font", style = "Regular" }
# normal = { family = "Hack Nerd Font", style = "Regular" }
# normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
# normal = { family = "BlexMono Nerd Font", style = "Regular" }
# normal = { family = "ZedMono Nerd Font", style = "Regular" }
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
# normal = { family = "Terminess Nerd Font", style = "Regular" }
normal = { family = "Ioskeley Mono Term Nerd Font", style = "Regular" }

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
